# PyTorch Tensors

- Each element is a 4 byte floating point number
- Can utilize GPUs for fast operations
- Values in tensors are allocated in chuncks of memory managed by torch.Storage
  - one-dimensional array of numerical data

In [1]:
import torch

In [2]:
# Initalize a tensor with 3 ones
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
# Intialize tensor providing a tuple as the size
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
# Construct a 2D triangle
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [6]:
points.shape

torch.Size([3, 2])

In [8]:
# All rows after the first, implicitly all columns
print(points[1:])

tensor([[5., 3.],
        [2., 1.]])


In [9]:
# All rows after the first, all column values
print(points[1:, :])

tensor([[5., 3.],
        [2., 1.]])


In [10]:
# All rows after the first, only the first column values
print(points[1:, 0])

tensor([5., 2.])


In [11]:
# Add a dimension of size 1
print(points[None])

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [13]:
# Ex. shape [batch, channels, rows, columns]
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[-0.5322,  0.8772, -0.8061, -0.9130, -0.3294],
          [-0.7709,  0.8128,  1.6721,  0.2456,  1.9444],
          [ 0.2071,  0.6276, -0.9516, -0.4035,  0.8575],
          [ 0.1403, -0.9770, -0.3081, -0.4448, -1.3909],
          [ 0.4786, -0.3332, -0.2640,  0.3662, -0.3592]],

         [[ 0.5413,  0.0168,  0.3898,  0.6633, -2.3648],
          [-2.3044, -0.5054, -0.6126,  0.1536, -0.4766],
          [ 1.6514,  0.5578, -1.2248, -0.7890,  0.3331],
          [-0.0640, -0.4744, -0.7596,  0.4438, -1.3697],
          [ 1.8617, -0.1158, -2.2349, -1.8298, -0.9083]],

         [[-1.0509, -1.2226,  0.6812,  0.2379,  0.3900],
          [ 0.3483, -0.9094, -0.3305, -0.6770, -0.1387],
          [ 0.4686, -0.2652,  0.7282,  0.2491,  0.6459],
          [ 0.3178,  0.1015,  0.7621, -0.2223, -0.1075],
          [-0.2586, -1.9047, -0.5189,  1.1505, -1.4378]]],


        [[[-0.4072,  1.4511,  1.0675,  1.3645,  0.0182],
          [-0.4996,  1.0942,  0.2072, -0.8047,  0.0799],
          [ 0.4747, -0.

In [14]:
# Creating a named tensor
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

C:\Users\Thomas\AppData\Local\Temp\ipykernel_19592\359375919.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1791.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [20]:
# Specify the data type 
double_points = torch.ones(10, 2, dtype = torch.short)
double_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [21]:
# Casting the data type
double_points = torch.zeros(10, 2).to(torch.short)
double_points

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

In [25]:
# Transpose a tensor
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [28]:
# Accessing storage
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [29]:
points_storage = points.storage()
points_storage[0]

4.0

In [30]:
# Modifying tensor through storage
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
# Modifying the tensor inplace
a = torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])