# PyTorch Tensors

- Each element is a 4 byte floating point number
- Can utilize GPUs for fast operations
- Values in tensors are allocated in chuncks of memory managed by torch.Storage
  - one-dimensional array of numerical data
- Accessing an element i, j in a 2D tensor is storage_offset + stride[0] * i + stride[1] * j element in storage
- When transposing a tensor, no new memory is allocated: transposing is obtained by creating a new tensor instance with a different stride ordering than the original

In [2]:
import torch

In [3]:
# Initalize a tensor with 3 ones
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
# Intialize tensor providing a tuple as the size
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
# Construct a 2D triangle
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [7]:
points.shape

torch.Size([3, 2])

In [8]:
# All rows after the first, implicitly all columns
print(points[1:])

tensor([[5., 3.],
        [2., 1.]])


In [9]:
# All rows after the first, all column values
print(points[1:, :])

tensor([[5., 3.],
        [2., 1.]])


In [10]:
# All rows after the first, only the first column values
print(points[1:, 0])

tensor([5., 2.])


In [11]:
# Add a dimension of size 1
print(points[None])

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [12]:
# Ex. shape [batch, channels, rows, columns]
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[-0.3946, -0.0732, -2.3651,  0.4809,  0.6796],
          [-0.5914,  1.7920,  0.2259,  0.8323,  0.1399],
          [-0.3840, -0.7885, -0.6600, -0.4225,  0.1822],
          [-0.2524,  0.7596, -0.9028,  0.7360,  2.1880],
          [-1.1783,  2.2969, -0.7238, -1.2732,  0.5356]],

         [[-0.6337, -0.5198, -0.0263,  2.4081, -0.6362],
          [ 0.1878,  0.1992,  1.0999,  0.2216, -0.9728],
          [-0.5193,  1.0447, -0.8477, -1.6430,  1.1237],
          [-0.4195, -0.5822, -1.4037, -0.6961, -0.0959],
          [ 0.1746,  0.0251,  1.1306,  1.3801, -0.1722]],

         [[ 0.1222,  1.2886, -0.0867,  1.9490, -2.3562],
          [ 1.2229, -1.0573,  0.4761,  0.0543, -0.1164],
          [ 1.3380, -1.6984,  0.8315,  1.6058,  0.1404],
          [-0.6183, -0.6691, -2.3299, -0.0272,  0.5170],
          [ 0.4455, -1.5494, -0.3728, -0.1547,  1.2741]]],


        [[[ 1.5829, -0.1393,  1.3696, -1.0367,  1.6458],
          [-0.0981,  0.4345, -1.0063,  0.3057,  0.0244],
          [ 0.3700,  1.

In [13]:
# Creating a named tensor
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

C:\Users\Thomas\AppData\Local\Temp\ipykernel_23020\359375919.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1791.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [14]:
# Specify the data type 
double_points = torch.ones(10, 2, dtype = torch.short)
double_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [15]:
# Casting the data type
double_points = torch.zeros(10, 2).to(torch.short)
double_points

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

In [16]:
# Transpose a tensor
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [17]:
# Accessing storage
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

C:\Users\Thomas\AppData\Local\Temp\ipykernel_23020\2812664130.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [18]:
points_storage = points.storage()
points_storage[0]

4.0

In [19]:
# Modifying tensor through storage
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points.stride()

(2, 1)

In [21]:
# Modifying the tensor inplace
a = torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
# Transpose
points_t = points.t()
points_t

tensor([[2., 5., 2.],
        [1., 3., 1.]])

In [31]:
# points and points_t share the same storage
id(points.storage()) == id(points_t.storage())

True

In [32]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [33]:
# Adding a tensor to GPU
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device = 'cuda')
# points_gpu = points.to(device='cuda')
# points_gpu = points.cuda()

In [34]:
# Tensor to NumPy array
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [36]:
# Numpy array to Tensor
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# 2 ways to save tensors
torch.save(points, '../data/chapter3/ourpoints.t')

with open('../data/chapter3/ourpoints.t','wb') as f:
	torch.save(points, f)

In [ ]:
# 2 ways to load a tensor
points = torch.load('../data/chapter3/ourpoints.t')

with open('../data/chapter3/ourpoints.t','rb') as f:
	points = torch.load(f)

## Exercises

In [50]:
a = list(range(9))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [51]:
a_tensor = torch.tensor(a)
a_tensor.size()

torch.Size([9])

In [52]:
a_tensor.storage_offset()

0

In [53]:
a_tensor.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [54]:
a_tensor.stride()

(1,)

In [74]:
b = a_tensor.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [71]:
id(a_tensor.storage()) == id(b.storage())

False

In [75]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [78]:
c.size()

torch.Size([2, 2])

In [79]:
c.storage_offset()

4

In [80]:
c.stride()

(3, 1)

In [81]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [84]:
torch.sqrt_(a_tensor)

RuntimeError: result type Float can't be cast to the desired output type Long